CREATE SCHEMA "SALES_TUTORIAL";

-- Create the region table
CREATE COLUMN TABLE "SALES_TUTORIAL"."REGION"(
	"REGION_ID" INTEGER,
	"REGION_NAME" VARCHAR(100),
	"SUB_REGION_NAME" VARCHAR(100),
	CONSTRAINT PK_REGION PRIMARY KEY ("REGION_ID")
);

-- Create the product table
CREATE COLUMN TABLE "SALES_TUTORIAL"."PRODUCT"(
	"PRODUCT_ID" INTEGER,
	"PRODUCT_NAME" VARCHAR(100),
	CONSTRAINT PK_PRODUCT PRIMARY KEY ("PRODUCT_ID")
);

-- Create the sales table
CREATE COLUMN TABLE "SALES_TUTORIAL"."SALES"(
	"REGION_ID" INTEGER,
	"PRODUCT_ID" INTEGER,
	"SALES_AMOUNT" DOUBLE,
	CONSTRAINT FK_REGION_SALES FOREIGN KEY ("REGION_ID") 
		REFERENCES "SALES_TUTORIAL"."REGION"("REGION_ID"),
	CONSTRAINT FK_PRODUCT_SALES FOREIGN KEY ("PRODUCT_ID") 
		REFERENCES "SALES_TUTORIAL"."PRODUCT"("PRODUCT_ID")
);

CREATE VIEW "SALES_TUTORIAL"."REGION_VIEW" AS
SELECT "REGION"."REGION_ID", "REGION"."REGION_NAME", "REGION"."SUB_REGION_NAME"
FROM "SALES_TUTORIAL"."REGION";

CREATE VIEW "SALES_TUTORIAL"."PRODUCT_VIEW" AS
SELECT "PRODUCT"."PRODUCT_ID", "PRODUCT"."PRODUCT_NAME"
FROM "SALES_TUTORIAL"."PRODUCT";

CREATE VIEW "SALES_TUTORIAL"."SALES_VIEW" AS
SELECT "SALES"."REGION_ID", "SALES"."PRODUCT_ID", "SALES"."SALES_AMOUNT"
FROM "SALES_TUTORIAL"."SALES";

-- Necessary to build/active modeling views 
GRANT SELECT ON SCHEMA "SALES_TUTORIAL" to _SYS_REPO WITH GRANT OPTION;